import type { FlowNode as RuntimeFlowNode } from "../../../../lib/flow-runtime/index.ts";
import type { PluginValue } from "../../../../runtime/plugins/sdk.ts";
import { encodedPluginValueBytes } from "../../../../runtime/plugins/schema.ts";
import { AiRuntimeError } from "../errors.ts";
import type { RuntimeEvent } from "../runtime-types.ts";
import { hookRecord, toHookValue } from "./HookValues.ts";
import type { PluginManager } from "./PluginManager.ts";

export class FlowHookPipeline {
  private readonly states = new Map<string, PluginValue>(); private readonly entered = new Map<string, string[]>();
  constructor(private readonly hookIds: readonly string[], private readonly manager: PluginManager, private readonly signal: AbortSignal, private readonly emit: (event: RuntimeEvent) => void) { for (const id of hookIds) this.states.set(id, null); }
  private key(nodeId: string, attempt: number) { return `${nodeId}:${attempt}`; }
  private base(hookId: string, node: Readonly<RuntimeFlowNode>, variables: Readonly<Record<string, unknown>>, inputs: readonly unknown[]) { return toHookValue({ node: { id: node.id, title: node.title ?? node.id, type: node.type, config: node.config ?? {} }, variables, inputs, state: this.states.get(hookId) ?? null }) as Record<string, PluginValue>; }
  private applyState(hookId: string, result: Record<string, PluginValue>) { if (!Object.hasOwn(result, "state")) return; const state = result.state ?? null; if (encodedPluginValueBytes(state) > 262_144) throw new AiRuntimeError("FLOW_HOOK_STATE_TOO_LARGE", `Flow Hook ${hookId} state exceeds 256 KiB`); this.states.set(hookId, state); }
  private async invoke(hookId: string, operation: string, nodeId: string, event: Record<string, PluginValue>, signal = this.signal) { if (!this.manager.hasFlowHookOperation(hookId, operation)) return {}; const startedAt = Date.now(); this.emit({ type: "flow-hook", hookId, nodeId, stage: operation, status: "start" }); try { const result = hookRecord(await this.manager.runFlowHook(hookId, operation, event, signal)); this.applyState(hookId, result); this.emit({ type: "flow-hook", hookId, nodeId, stage: operation, status: "complete", elapsedMs: Date.now() - startedAt }); return result; } catch (error) { this.emit({ type: "flow-hook", hookId, nodeId, stage: operation, status: "error", elapsedMs: Date.now() - startedAt }); throw new AiRuntimeError("FLOW_HOOK_FAILED", `Flow Hook ${hookId}.${operation} failed: ${error instanceof Error ? error.message : String(error)}`, { cause: error }); } }
  async beforeNode(event: { node: Readonly<RuntimeFlowNode>; attempt: number; variables: Readonly<Record<string, unknown>>; inputs: readonly unknown[]; signal: AbortSignal }) { let config = hookRecord(toHookValue(event.node.config ?? {})); const entered: string[] = []; for (const hookId of this.hookIds) { entered.push(hookId); const result = await this.invoke(hookId, "beforeNode", event.node.id, { ...this.base(hookId, { ...event.node, config }, event.variables, event.inputs), attempt: event.attempt }, event.signal); if (Object.hasOwn(result, "config")) { if (!result.config || typeof result.config !== "object" || Array.isArray(result.config)) throw new AiRuntimeError("FLOW_HOOK_CONFIG_INVALID", `Flow Hook ${hookId} config must be an object`); config = result.config as Record<string, PluginValue>; } if (Object.hasOwn(result, "skipWith")) { this.entered.set(this.key(event.node.id, event.attempt), entered); return { config, skip: true, output: result.skipWith }; } } this.entered.set(this.key(event.node.id, event.attempt), entered); return { config }; }
  async afterNode(event: { node: Readonly<RuntimeFlowNode>; attempt: number; variables: Readonly<Record<string, unknown>>; inputs: readonly unknown[]; signal: AbortSignal; output: unknown; skipped: boolean; recovered: boolean }) { let output = toHookValue(event.output); const entered = this.entered.get(this.key(event.node.id, event.attempt)) ?? [...this.hookIds]; this.entered.delete(this.key(event.node.id, event.attempt)); for (const hookId of [...entered].reverse()) { const result = await this.invoke(hookId, "afterNode", event.node.id, { ...this.base(hookId, event.node, event.variables, event.inputs), attempt: event.attempt, output, skipped: event.skipped, recovered: event.recovered }, event.signal); if (Object.hasOwn(result, "output")) output = result.output ?? null; } return output; }
  async onNodeError(event: { node: Readonly<RuntimeFlowNode>; attempts: number; variables: Readonly<Record<string, unknown>>; inputs: readonly unknown[]; signal: AbortSignal; error: Error }) { let recovered = false; let output: PluginValue = null; const error = event.error as Error & { code?: unknown }; for (const hookId of [...this.hookIds].reverse()) { const result = await this.invoke(hookId, "onNodeError", event.node.id, { ...this.base(hookId, event.node, event.variables, event.inputs), attempts: event.attempts, error: toHookValue({ name: error.name, ...(error.code ? { code: String(error.code) } : {}), message: error.message }) }, event.signal); if (!recovered && Object.hasOwn(result, "recoverWith")) { recovered = true; output = result.recoverWith ?? null; } } return recovered ? { recover: true, output } : undefined; }
}
