import { contentToText, type WorkspaceAgentReply, type WorkspaceToolCall, type WorkspaceToolEvent } from "../../../../lib/workspace-tool-calling.ts";
import type { PluginValue } from "../../../../runtime/plugins/sdk.ts";
import { AiRuntimeError } from "../errors.ts";
import type { RuntimeEvent } from "../runtime-types.ts";
import { normalizedHookMessage, toHookValue, type HookTool } from "./HookValues.ts";
import type { PluginManager } from "./PluginManager.ts";
import { WorkspaceHookContext } from "./WorkspaceHookContext.ts";
export type { HookTool } from "./HookValues.ts";

export class WorkspaceHookPipeline {
  private readonly enteredTools = new Map<WorkspaceToolCall, string[]>(); private readonly context: WorkspaceHookContext; stage: "workspace" | "model" | "tool" = "workspace"; iteration = 0;
  constructor(workspaceId: string, hookIds: readonly string[], variables: Readonly<Record<string, unknown>>, manager: PluginManager, signal: AbortSignal, emit: (event: RuntimeEvent) => void) { this.context = new WorkspaceHookContext(workspaceId, hookIds, variables, manager, signal, emit); }
  get variables() { return this.context.variables; }
  private invoke(hookId: string, operation: string, event: Record<string, PluginValue>) { return this.context.invoke(hookId, operation, this.iteration, event); }
  private get hookIds() { return this.context.hookIds; }
  async start(input: string) { this.stage = "workspace"; let current = input; for (const hookId of this.hookIds) { const result = await this.invoke(hookId, "onStart", toHookValue({ input: current }) as Record<string, PluginValue>); if (typeof result.input === "string") current = result.input; } return current; }
  async beforeModel(input: string, messages: readonly unknown[], tools: readonly HookTool[], forceFinal: boolean) { this.stage = "model"; const instructions: string[] = []; for (const hookId of this.hookIds) { const result = await this.invoke(hookId, "beforeModel", toHookValue({ input, forceFinal, messages: messages.map(normalizedHookMessage), tools }) as Record<string, PluginValue>); if (typeof result.systemInstruction === "string" && result.systemInstruction) instructions.push(result.systemInstruction); } return instructions; }
  async afterModel(reply: WorkspaceAgentReply, forceFinal: boolean, resolveTool: (call: WorkspaceToolCall) => HookTool) { this.stage = "model"; let content = contentToText(reply.content); const original = content; const toolCalls = (reply.toolCalls ?? []).map((call) => ({ ...resolveTool(call), ...(call.id ? { callId: call.id } : {}), input: toHookValue(call.args ?? {}) })); for (const hookId of [...this.hookIds].reverse()) { const result = await this.invoke(hookId, "afterModel", toHookValue({ forceFinal, content, toolCalls }) as Record<string, PluginValue>); if (typeof result.content === "string") content = result.content; } if (content === original) return reply; const raw = reply.raw && typeof reply.raw === "object" ? Object.assign(Object.create(Object.getPrototypeOf(reply.raw)), reply.raw, { content }) : { role: "assistant", content, tool_calls: reply.toolCalls ?? [] }; return { ...reply, content, raw }; }
  async beforeTool(event: WorkspaceToolEvent & { rawInput: unknown }) { this.stage = "tool"; let input = toHookValue(event.rawInput); const entered: string[] = []; for (const hookId of this.hookIds) { entered.push(hookId); const result = await this.invoke(hookId, "beforeTool", toHookValue({ tool: { id: event.toolId, name: event.toolName, kind: event.kind }, ...(event.call.id ? { callId: event.call.id } : {}), input }) as Record<string, PluginValue>); if (Object.hasOwn(result, "input")) input = result.input ?? null; if (typeof result.skipWith === "string") { this.enteredTools.set(event.call, entered); return { input, skipWith: result.skipWith }; } } this.enteredTools.set(event.call, entered); return { input }; }
  async afterTool(event: WorkspaceToolEvent & { rawInput: unknown; output: string; skipped: boolean }) { this.stage = "tool"; let output = event.output; const entered = this.enteredTools.get(event.call) ?? [...this.hookIds]; this.enteredTools.delete(event.call); for (const hookId of [...entered].reverse()) { const result = await this.invoke(hookId, "afterTool", toHookValue({ tool: { id: event.toolId, name: event.toolName, kind: event.kind }, ...(event.call.id ? { callId: event.call.id } : {}), input: toHookValue(event.rawInput), output, skipped: event.skipped }) as Record<string, PluginValue>); if (typeof result.output === "string") output = result.output; } return { output }; }
  async finish(output: string) { this.stage = "workspace"; let current = output; for (const hookId of [...this.hookIds].reverse()) { const result = await this.invoke(hookId, "onFinish", toHookValue({ output: current }) as Record<string, PluginValue>); if (typeof result.output === "string") current = result.output; } return current; }
  async error(error: unknown, tool?: HookTool) { if (error instanceof AiRuntimeError && error.code === "WORKSPACE_HOOK_FAILED") return; const value = error as { name?: unknown; code?: unknown; message?: unknown }; for (const hookId of [...this.hookIds].reverse()) await this.invoke(hookId, "onError", toHookValue({ stage: this.stage, error: { name: String(value?.name ?? "Error"), ...(value?.code ? { code: String(value.code) } : {}), message: String(value?.message ?? error) }, ...(tool ? { tool } : {}) }) as Record<string, PluginValue>); }
}
