import type { AppInteractionConfig, FlowProject } from "../../../domain/flow/types.ts";
import { validateExpression } from "../../../lib/flow-runtime/expression.ts";
import { outputKindForCode, type CodeDefinition, type CodeValue } from "./code.ts";
import { addFlowNode, createFlowGraph, finishFlow, registerVariable, type FlowGraphState } from "./flow-graph.ts";
import type { WorkspaceHookDefinition } from "./hook.ts";
import { BRANCH_REF } from "./model-symbols.ts";
import type { CodeNodeOptions, ConditionBranchRef, ConditionNodeOptions, ConditionRef, ContactNodeOptions, ContactReceipt, FlowBuilderApi, FlowFinishIdentity, HttpNodeOptions, InputNodeOptions, NodeRef, OutputNodeOptions, PreparedApp, SkillDefinition, SkillNodeOptions, VariableRef, Visualization, WorkspaceNodeOptions } from "./model-types.ts";
import { fail, inferredKind, serializeValue, template } from "./model-values.ts";

export class FlowBuilder implements FlowBuilderApi {
  private readonly graph: FlowGraphState;
  private readonly skillIds: Set<string>;
  private readonly codeDefinitions = new Map<string, CodeDefinition>();
  private readonly hookDefinitions = new Map<string, WorkspaceHookDefinition>();
  constructor(initial: readonly VariableRef<unknown>[], skills: readonly SkillDefinition[]) { this.graph = createFlowGraph(initial); this.skillIds = new Set(skills.map((skill) => skill.id)); }
  input(options: InputNodeOptions) { if (!options.fields.length) fail("INVALID_INPUT", `输入节点“${options.id}”至少需要一个字段`, { nodeId: options.id }); const seen = new Set<string>(); for (const field of options.fields) { registerVariable(this.graph, field.variable); if (seen.has(field.variable.name)) fail("INVALID_INPUT", `输入节点“${options.id}”重复使用变量“${field.variable.name}”`, { nodeId: options.id }); seen.add(field.variable.name); } const fields = options.fields.map((field, index) => ({ id: `field_${field.variable.name}_${index}`, variable: field.variable.name, label: field.label, component: field.component ?? (field.variable.kind === "boolean" ? "checkbox" : "input"), size: field.size ?? (field.variable.kind === "boolean" ? "small" : "large"), ...(field.placeholder !== undefined ? { placeholder: field.placeholder } : {}), ...(field.buttonValue !== undefined ? { buttonValue: field.buttonValue } : {}) })); const result = addFlowNode(this.graph, "INPUT", options, { layout: options.layout ?? "single", fields }, [], "object", { note: [...seen].join(", ") }); for (const name of seen) this.graph.producers.set(name, options.id); return result; }
  skill<T = string>(options: SkillNodeOptions<T>) { if (!this.skillIds.has(options.skill.id)) fail("MISSING_SKILL", `节点“${options.id}”使用了未在 App 中声明的 Skill “${options.skill.id}”`, { nodeId: options.id }); const input = options.input ?? "{{user_input}}"; return addFlowNode(this.graph, "SKILL", options, { skillId: options.skill.id, input: serializeValue(input) }, input, "markdown", { note: options.skill.id }); }
  workspace<T = string>(options: WorkspaceNodeOptions<T>) { if (!this.skillIds.has(options.agent.id)) fail("MISSING_SKILL", `Workspace“${options.id}”的总 Agent Skill 未在 App 中声明`, { nodeId: options.id }); if (!options.skills.length) fail("INVALID_WORKSPACE", `Workspace“${options.id}”至少需要一个可调用 Skill`, { nodeId: options.id }); if (options.skills.some((skill) => skill.id === options.agent.id)) fail("INVALID_WORKSPACE", `Workspace“${options.id}”不能把总 Agent 同时设为可调用 Skill`, { nodeId: options.id }); for (const skill of options.skills) if (!this.skillIds.has(skill.id)) fail("MISSING_SKILL", `Workspace“${options.id}”使用了未声明的 Skill “${skill.id}”`, { nodeId: options.id }); const maxIterations = options.maxIterations ?? 6; if (!Number.isInteger(maxIterations) || maxIterations < 1 || maxIterations > 10) fail("INVALID_WORKSPACE", `Workspace“${options.id}”的 maxIterations 必须为 1–10`, { nodeId: options.id }); const hooks = [...(options.hooks ?? [])]; if (hooks.length > 16) fail("INVALID_WORKSPACE_HOOKS", `Workspace“${options.id}”最多声明 16 个 Hook`, { nodeId: options.id }); const ids = new Set<string>(); for (const hook of hooks) { if (ids.has(hook.id)) fail("DUPLICATE_WORKSPACE_HOOK", `Workspace“${options.id}”重复声明 Hook “${hook.id}”`, { nodeId: options.id }); ids.add(hook.id); const current = this.hookDefinitions.get(hook.id); if (current && current !== hook) fail("DUPLICATE_WORKSPACE_HOOK", `Hook ID “${hook.id}”引用了不同定义`, { nodeId: options.id }); this.hookDefinitions.set(hook.id, hook); } const input = options.input ?? "{{user_input}}"; const workspace = { agentSkillId: options.agent.id, skillIds: options.skills.map((skill) => skill.id), maxIterations }; return addFlowNode(this.graph, "WORKSPACE", options, { ...workspace, input: serializeValue(input), ...(hooks.length ? { hookIds: hooks.map((hook) => hook.id) } : {}) }, input, "markdown", { workspace, note: `${options.agent.id} · ${options.skills.length} Skills` }); }
  http<T = unknown>(options: HttpNodeOptions<T>) { const source = { url: options.url, headers: options.headers, body: options.body }; return addFlowNode(this.graph, "HTTP", options, { method: options.method ?? "GET", url: serializeValue(options.url), ...(options.headers === undefined ? {} : { headers: serializeValue(options.headers) }), ...(options.body === undefined ? {} : { body: serializeValue(options.body) }) }, source, "object"); }
  condition(options: ConditionNodeOptions): ConditionRef { const expression = String(serializeValue(options.expression)); const error = validateExpression(expression); if (error) fail("INVALID_CONDITION", `条件节点“${options.id}”表达式无效：${error}`, { nodeId: options.id }); const output = addFlowNode(this.graph, "CONDITION", options, { expression }, options.expression, "boolean"); const branch = (condition: "true" | "false"): ConditionBranchRef => Object.freeze({ nodeId: output.nodeId, condition, [BRANCH_REF]: true as const }); return Object.freeze({ ...output, whenTrue: () => branch("true"), whenFalse: () => branch("false") }) as ConditionRef; }
  code<TInput extends CodeValue, TOutput extends CodeValue>(options: CodeNodeOptions<TInput, TOutput>): NodeRef<TOutput> { const current = this.codeDefinitions.get(options.code.id); if (current && current !== options.code) fail("DUPLICATE_CODE", `Code ID “${options.code.id}”引用了不同定义`, { path: options.code.id }); this.codeDefinitions.set(options.code.id, options.code as CodeDefinition); return addFlowNode(this.graph, "CODE", options, { codeId: options.code.id, input: serializeValue(options.input) }, options.input, outputKindForCode(options.code.outputSchema), { note: options.code.id }); }
  contact(options: ContactNodeOptions): NodeRef<ContactReceipt> { const source = { title: options.title, body: options.body, dedupeKey: options.dedupeKey }; return addFlowNode(this.graph, "CONTACT", options, { title: serializeValue(options.title), body: serializeValue(options.body), severity: options.severity ?? "info", webhook: options.webhook === true, ...(options.dedupeKey === undefined ? {} : { dedupeKey: serializeValue(options.dedupeKey) }) }, source, "object"); }
  output<T = unknown>(options: OutputNodeOptions<T>) { const value = options.value ?? template`{{previous.output}}`; return addFlowNode(this.graph, "OUTPUT", options, { template: serializeValue(value) }, value, inferredKind(value)); }
  finish(name: string, skills: readonly SkillDefinition[], visualizations: readonly Visualization[], interaction?: AppInteractionConfig, identity?: FlowFinishIdentity, execution?: FlowProject["execution"]): PreparedApp["project"] { return finishFlow(this.graph, name, skills, visualizations, interaction, identity, execution); }
  codes() { return [...this.codeDefinitions.values()]; }
  hooks() { return [...this.hookDefinitions.values()]; }
}
