import { autoLayoutNodes, createConnection } from "../../../domain/flow/editor.ts";
import type { AppInteractionConfig, FlowNode, FlowProject, Variable } from "../../../domain/flow/types.ts";
import { VALUE_REF } from "./model-symbols.ts";
import type { After, CommonNodeOptions, FlowFinishIdentity, NodeRef, OutputOption, Position, PreparedApp, SdkFlowNode, SkillDefinition, VariableKind, VariableRef, Visualization } from "./model-types.ts";
import { assertId, collectReferenceNames, defaultFor, encodeDefault, fail, isBranchRef, isNodeRef, isTemplate, isValueRef, RESERVED_VARIABLES, variableRef } from "./model-values.ts";

export type FlowGraphState = { id: string; nodes: SdkFlowNode[]; edges: FlowProject["edges"]; variables: Map<string, VariableRef<unknown>>; producers: Map<string, string>; positions: Map<string, Position>; branchConsumers: Map<string, string>; lastNodeId: string };
const styles: Record<SdkFlowNode["type"], { title: string; icon: string; tone: string; note: string }> = {
  START: { title: "开始", icon: "▶", tone: "mint", note: "流程入口" }, INPUT: { title: "用户输入", icon: "⌨", tone: "blue", note: "收集运行变量" }, SKILL: { title: "调用 Skill", icon: "✦", tone: "violet", note: "调用 Skill" }, WORKSPACE: { title: "Agent Workspace", icon: "◎", tone: "cyan", note: "Agent 自主调用 Skills" }, HTTP: { title: "HTTP 请求", icon: "⌁", tone: "slate", note: "发送 HTTPS 请求" }, CONDITION: { title: "条件分支", icon: "◇", tone: "amber", note: "运行时条件判断" }, CODE: { title: "TypeScript 代码", icon: "{ }", tone: "slate", note: "执行确定性代码" }, CONTACT: { title: "联系用户", icon: "@", tone: "cyan", note: "写入 Inbox 并投递通知" }, OUTPUT: { title: "输出", icon: "↗", tone: "green", note: "返回运行结果" },
};
export function createFlowGraph(initial: readonly VariableRef<unknown>[]): FlowGraphState { const start = styles.START; const state: FlowGraphState = { id: crypto.randomUUID(), nodes: [{ id: "start", title: start.title, type: "START", icon: start.icon, x: 24, y: 180, tone: start.tone, note: start.note, outputVar: "" }], edges: [], variables: new Map(), producers: new Map(), positions: new Map(), branchConsumers: new Map(), lastNodeId: "start" }; initial.forEach((ref) => registerVariable(state, ref)); return state; }
export function registerVariable(state: FlowGraphState, ref: VariableRef<unknown>) { const current = state.variables.get(ref.name); if (current && (current.kind !== ref.kind || encodeDefault(current) !== encodeDefault(ref))) fail("DUPLICATE_VARIABLE", `变量“${ref.name}”使用了冲突的类型或默认值`, { path: ref.name }); if (!current) state.variables.set(ref.name, ref); }
function registerNested(state: FlowGraphState, value: unknown) { if (isValueRef(value)) return registerVariable(state, value); if (Array.isArray(value)) return value.forEach((item) => registerNested(state, item)); if (value && typeof value === "object" && !isTemplate(value)) Object.values(value).forEach((item) => registerNested(state, item)); }
function outputRef<T>(state: FlowGraphState, nodeId: string, option: OutputOption<T> | undefined, kind: VariableKind): NodeRef<T> { const existing = typeof option === "string" ? state.variables.get(option) : option; const name = typeof option === "string" ? option : option?.name ?? `${nodeId}_output`; if (RESERVED_VARIABLES.has(name)) fail("RESERVED_VARIABLE", `节点“${nodeId}”不能写入 runtime 保留变量“${name}”`, { nodeId }); const ref = existing ?? variableRef(kind, name, defaultFor(kind) as T); registerVariable(state, ref); const producer = state.producers.get(name); if (producer && producer !== nodeId) fail("DUPLICATE_OUTPUT", `输出变量“${name}”已由节点“${producer}”写入`, { nodeId }); state.producers.set(name, nodeId); return Object.freeze({ ...ref, id: nodeId, nodeId, [VALUE_REF]: "node" as const, __builderId: state.id }) as NodeRef<T>; }
function explicitDependencies(state: FlowGraphState, refs: readonly import("./model-types.ts").AfterRef[], nodeId: string, result: Map<string, "true" | "false" | undefined>) { for (const ref of refs) { if (isBranchRef(ref)) { if (state.nodes.find((node) => node.id === ref.nodeId)?.type !== "CONDITION") fail("INVALID_DEPENDENCY", `节点“${nodeId}”引用了无效的条件分支`, { nodeId }); const key = `${ref.nodeId}:${ref.condition}`; const consumer = state.branchConsumers.get(key); if (consumer && consumer !== nodeId) fail("DUPLICATE_BRANCH_CONSUMER", `条件节点“${ref.nodeId}”的 ${ref.condition} 分支已连接节点“${consumer}”`, { nodeId }); state.branchConsumers.set(key, nodeId); result.set(ref.nodeId, ref.condition); continue; } if (!isNodeRef(ref) || !state.nodes.some((node) => node.id === ref.nodeId)) fail("INVALID_DEPENDENCY", `节点“${nodeId}”引用了其他流程或尚未创建的依赖`, { nodeId }); if (state.nodes.find((node) => node.id === ref.nodeId)?.type === "CONDITION") fail("CONDITION_BRANCH_REQUIRED", `节点“${nodeId}”必须通过 whenTrue() 或 whenFalse() 连接条件节点`, { nodeId }); result.set(ref.nodeId, result.get(ref.nodeId)); } }
function dependencies(state: FlowGraphState, source: unknown, after: After | undefined, nodeId: string) { registerNested(state, source); const result = new Map<string, "true" | "false" | undefined>(); for (const name of collectReferenceNames(source)) { const producer = state.producers.get(name); if (producer) result.set(producer, undefined); } if (after !== undefined) explicitDependencies(state, Array.isArray(after) ? after : [after], nodeId, result); else if (!result.size) result.set(state.lastNodeId, undefined); if (after !== undefined && !result.size) result.set("start", undefined); result.delete(nodeId); return [...result]; }
export function addFlowNode<T>(state: FlowGraphState, type: Exclude<SdkFlowNode["type"], "START">, options: CommonNodeOptions<T>, config: Record<string, unknown>, source: unknown, kind: VariableKind, details: { note?: string; workspace?: FlowNode["workspace"] } = {}) { assertId(options.id, "Node"); if (options.id === "start" || state.nodes.some((node) => node.id === options.id)) fail("DUPLICATE_NODE", `节点 ID “${options.id}” 重复`, { nodeId: options.id }); const refs = dependencies(state, source, options.after, options.id); const output = outputRef(state, options.id, options.output, kind); const style = styles[type]; const timeoutMs = options.timeoutMs; if (timeoutMs !== undefined && (!Number.isInteger(timeoutMs) || timeoutMs < 1 || timeoutMs > 600_000)) fail("INVALID_EXECUTION_LIMIT", `节点“${options.id}”的 timeoutMs 必须为 1–600000 的整数`); state.nodes.push({ id: options.id, title: options.title?.trim() || style.title, type, icon: style.icon, x: options.position?.x ?? 0, y: options.position?.y ?? 0, tone: style.tone, note: details.note ?? style.note, outputVar: output.name, config, ...(timeoutMs !== undefined ? { timeoutMs } : {}), ...(details.workspace ? { workspace: details.workspace } : {}) }); if (options.position) state.positions.set(options.id, options.position); for (const [from, condition] of refs) { const edge = createConnection(from, options.id, state.edges); state.edges.push(condition ? { ...edge, label: condition, condition } : edge); } state.lastNodeId = options.id; return output; }
export function finishFlow(state: FlowGraphState, name: string, skills: readonly SkillDefinition[], visualizations: readonly Visualization[], interaction?: AppInteractionConfig, identity?: FlowFinishIdentity, execution?: FlowProject["execution"]): PreparedApp["project"] { const nodes = autoLayoutNodes(state.nodes as FlowNode[], state.edges).map((node) => { const position = state.positions.get(node.id); return position ? { ...node, ...position } : node; }); return { name, ...(identity?.id ? { appId: identity.id } : {}), ...(identity?.version ? { appVersion: identity.version } : {}), ...(interaction ? { interaction } : {}), ...(identity?.background ? { background: identity.background } : {}), ...(execution ? { execution } : {}), nodes: nodes as SdkFlowNode[], edges: state.edges, skills: skills.map((skill) => ({ id: skill.id, name: skill.name, description: skill.description, category: skill.category, prompt: isTemplate(skill.prompt) ? skill.prompt.text : skill.prompt, pluginIds: skill.plugins.map((plugin) => plugin.id) })), variables: [...state.variables.values()].map((ref): Variable => ({ name: ref.name, type: ref.kind, defaultValue: encodeDefault(ref) })), visualizations: [...visualizations] }; }
