// SPDX-License-Identifier: Elastic-2.0
import { randomUUID } from "node:crypto";
import { rm } from "node:fs/promises";
import { join } from "node:path";
import { AiRuntimeError, executeGatewayTrigger, type AiStreamEvent, type AiStreamMode, type BackgroundTriggerContext, type RuntimeOptions } from "@agcomm/ai-runtime/gateway-host";
import { STREAM_RETENTION_MS, type GatewayAppSummary, type GatewayRunRecord, type GatewayRunTicket, type GatewayState, type GatewayTrigger, type PendingRun } from "./GatewayState.ts";
import type { GatewayExecutionPort } from "./GatewayExecutionPort.ts";
import type { GatewayNotifier } from "./GatewayNotifier.ts";
import type { GatewayStream } from "./GatewayStream.ts";

const errorText = (error: unknown) => (error instanceof Error ? error.message : String(error)).slice(0, 4_096);
const summary = (value: unknown, limit = 4_096) => (typeof value === "string" ? value : JSON.stringify(value ?? null)).slice(0, limit);
type ExecutorServices = { state: GatewayState; stream: GatewayStream; notifier: GatewayNotifier; runtime?: RuntimeOptions; now(): Date };

/** Owns active runs, coalesced queues and trigger execution. */
export class GatewayExecutor implements GatewayExecutionPort {
  readonly active = new Map<string, AbortController>(); readonly activeRunIds = new Map<string, string>(); readonly pending = new Map<string, Map<string, PendingRun>>();
  private services?: ExecutorServices;
  configure(services: ExecutorServices) { this.services = services; }
  private service() { if (!this.services) throw new AiRuntimeError("GATEWAY_NOT_INITIALIZED", "Gateway executor is unavailable"); return this.services; }
  activeFor(app: GatewayAppSummary) { return this.active.has(app.id); }
  queue(app: GatewayAppSummary, pending: PendingRun) { const queue = this.pending.get(app.id) ?? new Map<string, PendingRun>(); const existing = queue.get(pending.trigger.id); if (!existing) { queue.set(pending.trigger.id, pending); this.pending.set(app.id, queue); } return existing; }
  release(record: GatewayRunRecord) { this.active.delete(record.appId); this.activeRunIds.delete(record.appId); }
  next(appId: string) { const queue = this.pending.get(appId); const next = queue?.values().next().value as PendingRun | undefined; if (next) { queue!.delete(next.trigger.id); if (!queue!.size) this.pending.delete(appId); } return next; }
  private completion(runId: string) { return this.service().stream.completion(runId); }
  private baseRecord(app: GatewayAppSummary, trigger: GatewayTrigger, scheduledAt: Date, runId: string, mode: AiStreamMode, status: "queued" | "running"): GatewayRunRecord { const now = this.service().now(); return { id: runId, appId: app.id, packageHash: app.packageHash, triggerId: trigger.id, triggerType: "everyMs" in trigger ? "heartbeat" : "cron", scheduledAt: scheduledAt.toISOString(), startedAt: now.toISOString(), status, streamMode: mode, lastSequence: 0, streamExpiresAt: new Date(now.getTime() + STREAM_RETENTION_MS).toISOString() }; }
  async cancelPending(id: string, reason: string) { const { state, stream, now } = this.service(); const queued = this.pending.get(id); this.pending.delete(id); if (!queued?.size) return; const at = now(); for (const pending of queued.values()) { const record = await state.runRecord(id, pending.runId); Object.assign(record, { status: "cancelled", finishedAt: at.toISOString(), elapsedMs: Math.max(0, at.getTime() - Date.parse(record.startedAt)), error: reason }); await state.upsertRun(id, record); stream.complete(record); } }
  async stopActive(id: string, reason: string) { const controller = this.active.get(id); const runId = this.activeRunIds.get(id); if (!controller || !runId) return; controller.abort(new DOMException(reason, "AbortError")); await this.completion(runId).promise; }
  async start(app: GatewayAppSummary, trigger: GatewayTrigger, scheduledAt: Date, mode: AiStreamMode): Promise<GatewayRunTicket> {
    const { state } = this.service();
    if (this.active.has(app.id)) { const runId = randomUUID(); const existing = this.queue(app, { runId, trigger, scheduledAt, mode }); if (existing) return { runId: existing.runId, status: "queued", coalesced: true }; this.completion(runId); await state.upsertRun(app.id, this.baseRecord(app, trigger, scheduledAt, runId, mode, "queued")); return { runId, status: "queued", coalesced: false }; }
    const controller = new AbortController(); const runId = randomUUID(); this.completion(runId); const record = this.baseRecord(app, trigger, scheduledAt, runId, mode, "running"); this.active.set(app.id, controller);
    try { await state.upsertRun(app.id, record); } catch (error) { this.active.delete(app.id); throw error; }
    this.activeRunIds.set(app.id, runId); this.launch(app, trigger, scheduledAt, record, controller); return { runId, status: "running", coalesced: false };
  }
  private previous(runs: GatewayRunRecord[], triggerId: string): BackgroundTriggerContext["previous"] { const run = [...runs].reverse().find((item) => item.triggerId === triggerId && (item.status === "completed" || item.status === "failed") && item.finishedAt); return run ? { status: run.status as "completed" | "failed", finishedAt: run.finishedAt!, ...(run.outputSummary ? { outputSummary: run.outputSummary } : {}) } : undefined; }
  private launch(app: GatewayAppSummary, trigger: GatewayTrigger, scheduledAt: Date, record: GatewayRunRecord, controller: AbortController) { void this.execute(app, trigger, scheduledAt, record, controller).catch((error) => this.failLaunch(app, record, controller, error)); }
  private async failLaunch(app: GatewayAppSummary, record: GatewayRunRecord, controller: AbortController, error: unknown) { const { state, stream, now } = this.service(); if (this.active.get(app.id) === controller) this.release(record); const current = await state.runRecord(app.id, record.id).catch(() => record); if (current.status !== "queued" && current.status !== "running") return; const reason = controller.signal.aborted ? controller.signal.reason ?? error : error; Object.assign(current, { status: reason instanceof DOMException && reason.name === "AbortError" ? "cancelled" : "failed", error: errorText(reason), finishedAt: now().toISOString(), elapsedMs: Math.max(0, now().getTime() - Date.parse(current.startedAt)) }); await state.upsertRun(app.id, current).catch(() => {}); stream.complete(current); }
  private async execute(app: GatewayAppSummary, trigger: GatewayTrigger, scheduledAt: Date, record: GatewayRunRecord, controller: AbortController) {
    const { state, stream, notifier, runtime, now } = this.service(); const started = now(); Object.assign(record, { status: "running", startedAt: started.toISOString() }); await state.upsertRun(app.id, record); const runs = await state.listRuns(app.id);
    const previous = this.previous(runs, trigger.id); const context: BackgroundTriggerContext = { type: "everyMs" in trigger ? "heartbeat" : "cron", id: trigger.id, scheduledAt: scheduledAt.toISOString(), firedAt: started.toISOString(), appId: app.id, packageHash: app.packageHash, runId: record.id, attempt: 1, ...(previous ? { previous } : {}) };
    await rm(state.streamPath(app.id, record.id), { force: true }); const streamState = stream.create(record, controller);
    try { const sessions = await state.triggerSessions(app.id); const session = sessions[trigger.id]?.packageHash === app.packageHash ? sessions[trigger.id] : { messages: [], packageHash: app.packageHash }; const result = await executeGatewayTrigger(join(state.appDirectory(app.id), "app.ai"), runtime, { input: trigger.input, variables: trigger.variables, signal: controller.signal, renderer: false, mode: record.streamMode, ...(record.streamMode === "events" ? { onStreamEvent: (event: AiStreamEvent) => { stream.append(streamState, event); } } : { onOutputDelta: (text: string) => { stream.append(streamState, text); } }) }, { trigger: context, history: session.messages, contact: (request) => notifier.recordContact(app, request) }); await streamState.tail; session.messages.push({ role: "user", content: trigger.input }, { role: "assistant", content: summary(result.output, 64_000) }); session.messages = session.messages.slice(-(app.background.historyWindow ?? 20)); sessions[trigger.id] = session; await state.saveTriggerSessions(app.id, sessions); record.status = "completed"; record.outputSummary = summary(result.output); }
    catch (error) { try { await streamState.tail; } catch (streamError) { error = streamError; } const reason = controller.signal.aborted ? controller.signal.reason ?? error : error; record.status = reason instanceof DOMException && reason.name === "AbortError" ? "cancelled" : "failed"; record.error = errorText(reason); }
    record.lastSequence = streamState.sequence; record.finishedAt = now().toISOString(); record.elapsedMs = now().getTime() - started.getTime(); await state.upsertRun(app.id, record); if (this.active.get(app.id) === controller) this.release(record); stream.complete(record); await stream.cleanup(app.id); await this.launchNext(app.id);
  }
  private async launchNext(appId: string) { const { state, stream, now } = this.service(); const next = this.next(appId); if (!next) return; const app = state.registry.apps.find((item) => item.id === appId && item.enabled); if (app) { const controller = new AbortController(); this.active.set(appId, controller); this.activeRunIds.set(appId, next.runId); this.launch(app, next.trigger, next.scheduledAt, await state.runRecord(appId, next.runId), controller); return; } const cancelled = await state.runRecord(appId, next.runId); Object.assign(cancelled, { status: "cancelled", finishedAt: now().toISOString(), elapsedMs: 0, error: "Gateway app is disabled" }); await state.upsertRun(appId, cancelled); stream.complete(cancelled); }
}
